# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt_core_news_sm
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    fallback_action_name: "explicando_algo"